FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install


# below not necessary if docker volume mounting/referencing but possibly keep it as a redundency
COPY . .

CMD ["npm", "run", "start"]